{{- if and (eq .Values.auth.type "basic") (not .Values.auth.basic.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ehrbase.fullname" . }}-auth-users
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
type: Opaque
data:
  admin-username: {{ .Values.auth.basic.adminUsername | b64enc }}
  admin-password: {{ .Values.auth.basic.adminPassword | default (randAlphaNum 32) | b64enc }}
  username: {{ .Values.auth.basic.username | b64enc }}
  password: {{ .Values.auth.basic.password | default (randAlphaNum 32) | b64enc }}
{{- end }}