apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ehrbase.fullname" . }}
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ehrbase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ehrbase.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ehrbase.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.postgresql.enabled }}
        - name: wait-for-postgres
          image: busybox:stable
          command: [ 'sh', '-c', 'until nc -z $POSTGRES_HOST $POSTGRES_PORT; do echo waiting for database; sleep 2; done;' ]
          env:
            - name: POSTGRES_HOST
              value: {{ include "ehrbase.databaseHost" .  | quote }}
            - name: POSTGRES_PORT
              value: {{ include "ehrbase.databasePort" .  | quote }}
        {{- end }}
      containers:
        - name: ehrbase
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "ehrbase.databaseSecretName" . }}
                  key: {{ include "ehrbase.databaseUserPasswordKey" . }}
            - name: DB_PASS_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "ehrbase.databaseSecretName" . }}
                  key: {{ include "ehrbase.databaseAdminPasswordKey" . }}
          envFrom:
            - configMapRef:
                name: {{ include "ehrbase.fullname" . }}-env-vars
          ports:
            {{- if not .Values.tls.enabled }}
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
              protocol: TCP
            {{- else }}
            - name: https
              containerPort: {{ .Values.containerPorts.https }}
              protocol: TCP
            {{- end }}
            - name: management
              containerPort: {{ .Values.containerPorts.management }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
            {{- if .Values.tls.enabled }}
            - name: tls-certs
              mountPath: /etc/tls
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp-dir
          emptyDir: { }
        {{- if .Values.tls.enabled }}
        - name: tls-certs
          secret:
            secretName: {{ .Values.tls.secretName }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
