{{- if and (not .Values.postgresql.enabled) (not .Values.externalPostgresql.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ehrbase.fullname" . }}-postgresql
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalPostgresql.password | default (randAlphaNum 32) | b64enc }}
{{- end }}