{{- if and (not .Values.redis.enabled) (not .Values.externalRedis.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ehrbase.fullname" . }}-redis
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.externalRedis.password | default (randAlphaNum 32) | b64enc }}
{{- end }}