apiVersion: v1
kind: Service
metadata:
  name: {{ include "ehrbase.fullname" . }}
  labels:
    {{- include "ehrbase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if not .Values.tls.enabled }}
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
    {{- else }}
    - name: https
      port: {{ .Values.service.ports.https }}
      targetPort: https
      protocol: TCP
    {{- end }}
    - name: management
      port: {{ .Values.service.ports.management }}
      targetPort: management
      protocol: TCP
  selector:
    {{- include "ehrbase.selectorLabels" . | nindent 4 }}
